/**
 * Domain types — shape of business entities as the app layer uses them.
 * DB row types live in src/lib/db/types.ts (generated by `supabase gen types`).
 */
import type { WeatherCategory } from '@/lib/config/thresholds';

export type MenuItem = {
  id: string;
  outletId: string;
  name: string;
  normalizedName: string;
  unit: string;
};

export type StockItem = {
  menuItemId: string;
  sold: number;
  leftover: number;
  unit: string;
};

export type StockLogStatus = 'pending' | 'parsed' | 'confirmed' | 'rejected';

export type StockDraft = {
  id: string;
  outletId: string;
  rawInput: string;
  serviceDate: string;
  status: StockLogStatus;
  parsedPayload: ParsedStockPayload | null;
  createdAt: string;
};

export type StockLog = {
  id: string;
  outletId: string;
  serviceDate: string;
  items: StockItem[];
  confirmedAt: string;
};

export type ParsedStockPayload = {
  items: Array<{
    menuItemId: string | null;
    candidateName: string;
    sold: number | null;
    leftover: number | null;
    unit: string | null;
    confidence: 'high' | 'medium' | 'low';
  }>;
  weatherMention: WeatherCategory | null;
  notes: string | null;
};

export type ConfidenceLabel = 'Pola jelas' | 'Data baru, hati-hati' | 'Tidak yakin';

export type RecommendationItem = {
  menuItemId: string;
  base: number;
  weatherFactor: number;
  weekdayFactor: number;
  suggested: number;
  confidenceLabel: ConfidenceLabel;
};

export type Recommendation = {
  id: string;
  outletId: string;
  serviceDate: string;
  items: RecommendationItem[];
  reasoning: string;
  confidenceLabel: ConfidenceLabel;
  createdAt: string;
};

export type PromoDraftStatus = 'draft' | 'copied' | 'dismissed';

export type PromoDraft = {
  id: string;
  outletId: string;
  serviceDate: string;
  message: string;
  discountPercent: number | null;
  status: PromoDraftStatus;
  createdAt: string;
};
